### ISSUE TITLE
%matplotlib notebook causes exception

### ISSUE THREAD

**Issue by rlabbe** [paulgb/runipy#115]
Perhaps this isn't so easy to support, but `%matplotlib notebook` allows for interactive plots. I have a small notebook that raises 

    NotImplementedError: unhandled iopub message: comm_open

if I have that statement in the first cell of my notebook. If I change it to `%notebook inline` I do not get the exception.

command line is

    runipy -o gibbs-sampling.ipynb

Environment: Windows 10 64-git, Python 3.5.1 64-bit, IPython 4.1.1, Anaconda package.

Example notebook that causes the exception; https://github.com/rlabbe/kruschke/blob/master/gibbs-sampling.ipynb

**Comment by jakirkham** [comment]
Yeah, this is another case of this issue ( https://github.com/paulgb/runipy/issues/32 ). Namely, interactive widgets are not supported. I was thinking of a solution like this ( https://github.com/paulgb/runipy/issues/110 ). So, these steps could be ignored as needed.

I think a real fix would require a rewrite of `runipy`. This rewrite may not be compatible with iPython 2.x so would require a major version change. That being said, this is requested enough and I also would like to have this; so, maybe it is time to simply make this change. At this point, I think I have solved all of the known bugs so making an enhancement like this and dropping iPython 2.x support would be ok. I took a look at what this might require last weekend and think it should be doable so once I have some time to write this I will do it.

**Comment by AlJohri** [comment]
just wanted to drop a note that I just encountered this as well trying to automatically update a notebook with bokeh visualizations

```
05/04/2016 02:29:48 PM INFO: Cell returned
Traceback (most recent call last):
  File "/Users/johria/anaconda3/bin/runipy", line 11, in <module>
    sys.exit(main())
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/runipy/main.py", line 158, in main
    nb_runner.run_notebook(skip_exceptions=args.skip_exceptions)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/runipy/notebook_runner.py", line 232, in run_notebook
    self.run_cell(cell)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/runipy/notebook_runner.py", line 208, in run_cell
    'unhandled iopub message: %s' % msg_type
NotImplementedError: unhandled iopub message: comm_open
```

**Comment by Juanlu001** [comment]
I also run into this while using Bokeh.

**Comment by jakirkham** [comment]
With Bokeh, my solution is to try and save HTML instead, @Juanlu001. Would that work for you?

**Comment by jakirkham** [comment]
As long as we are supporting IPython 2.x, these features are challenging to support. I've looked at trying to get support without that deprecation, but it is a lot of work that I don't really have time for. If deprecation of IPython 2.x is something that people would be ok with, please give me feedback in this issue ( https://github.com/paulgb/runipy/issues/78 ).

**Comment by Juanlu001** [comment]
We already have some workarounds in place for Bokeh @jakirkham, but I agree that supporting IPython 2.x is a barrier for this and other features. I will follow the conversation on #78.
