### ISSUE TITLE
HTML snapshot raises attribute error

### ISSUE THREAD

**Issue by adam-paul** [paulgb/runipy#119]
Thanks for this great python package! I am wondering if I could get any insight into an error that I can't make my way around when attempting to generate HTML reports with runipy.

The simplest case occurs with a basic test run with the html option as specified in the README: 

`runipy test.ipynb --html report.html`

The notebook executes fine, but upon generating the snapshot: 

```
05/03/2016 02:32:28 PM INFO: Cell returned
05/03/2016 02:32:28 PM INFO: Saving HTML snapshot to report.html
Traceback (most recent call last):
  File "/home/adam/anaconda2/bin/runipy", line 11, in <module>
    sys.exit(main())
  File "/home/adam/anaconda2/lib/python2.7/site-packages/runipy/main.py", line 204, in main
    output, resources = exporter.from_notebook_node(nb_runner.nb)
  File "/home/adam/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/adam/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 196, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/adam/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/adam/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/adam/anaconda2/lib/python2.7/site-packages/nbconvert/preprocessors/coalescestreams.py", line 29, in wrappedfunc
    for index, cell in enumerate(nb.cells):
  File "/home/adam/anaconda2/lib/python2.7/site-packages/ipython_genutils/ipstruct.py", line 134, in __getattr__
    raise AttributeError(key)
AttributeError: cells
```

Any idea what this might be about or how I could go about fixing it? Cheers!

**Comment by jakirkham** [comment]
Looks like you are using `conda`. Could you please run `conda list` and add that here?

**Comment by adam-paul** [comment]
Sure! Here is the result:

```
# packages in environment at /home/adam/anaconda2:
#
alabaster                 0.7.7                    py27_0  
anaconda                  4.0.0               np110py27_0  
anaconda-client           1.4.0                    py27_0  
anaconda-navigator        1.1.0                    py27_0  
argcomplete               1.0.0                    py27_1  
astropy                   1.1.2               np110py27_0  
babel                     2.2.0                    py27_0  
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.9.1                    py27_0  
bokeh                     0.11.1                   py27_0  
boto                      2.39.0                   py27_0  
bottleneck                1.0.0               np110py27_0  
cairo                     1.12.18                       6  
cdecimal                  2.3                      py27_0  
cffi                      1.5.2                    py27_0  
chest                     0.2.3                    py27_0  
cloudpickle               0.1.1                    py27_0  
clyent                    1.2.1                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.0.5                    py27_0  
conda-build               1.20.0                   py27_0  
conda-env                 2.4.5                    py27_0  
conda-manager             0.3.1                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              1.3                      py27_0  
curl                      7.45.0                        0  
cycler                    0.10.0                   py27_0  
cython                    0.23.4                   py27_0  
cytoolz                   0.7.5                    py27_0  
dask                      0.8.1                    py27_0  
datashape                 0.5.1                    py27_0  
decorator                 4.0.9                    py27_0  
dill                      0.2.4                    py27_0  
docutils                  0.12                     py27_0  
dynd                      0.7.3.dev1                <pip>
dynd-python               0.7.2                    py27_0  
enum34                    1.1.2                    py27_0  
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
flask-cors                2.1.2                    py27_0  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py27_0  
futures                   3.0.3                    py27_0  
gevent                    1.1.0                    py27_0  
greenlet                  0.4.9                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0               np110py27_4  
hdf5                      1.8.15.1                      2  
heapdict                  1.0.0                    py27_0  
idna                      2.0                      py27_0  
ipaddress                 1.0.14                   py27_0  
ipykernel                 4.3.1                    py27_0  
ipython                   4.1.2                    py27_1  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_0  
jedi                      0.9.0                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py27_0  
jupyter                   1.0.0                    py27_2  
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
libdynd                   0.7.2                         0  
libffi                    3.0.13                        0  
libgfortran               3.0                           0  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.9.0                    py27_0  
locket                    0.2.0                    py27_0  
lxml                      3.6.0                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.5.1               np110py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.1                        0  
mkl-service               1.1.2                    py27_0  
mpmath                    0.19                     py27_0  
multipledispatch          0.4.8                    py27_0  
nbconvert                 4.1.0                    py27_0  
nbformat                  4.0.1                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2                      py27_0  
nose                      1.3.7                    py27_0  
notebook                  4.1.0                    py27_1  
nugridpy                  0.1.5480                  <pip>
numba                     0.24.0              np110py27_0  
numexpr                   2.5                 np110py27_0  
numpy                     1.10.4                   py27_1  
odo                       0.4.2                    py27_0  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2g                        0  
pandas                    0.18.0              np110py27_0  
partd                     0.3.2                    py27_1  
patchelf                  0.8                           0  
path.py                   8.1.2                    py27_1  
patsy                     0.4.0               np110py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.5                      py27_0  
pillow                    3.1.1                    py27_0  
pip                       8.1.1                    py27_1  
pixman                    0.32.6                        0  
ply                       3.8                      py27_0  
psutil                    4.1.0                    py27_0  
ptyprocess                0.5                      py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.3                 py27_0  
pyflakes                  1.1.0                    py27_0  
pygments                  2.1.1                    py27_0  
pyopenssl                 0.15.1                   py27_2  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_1  
pytables                  3.2.2               np110py27_1  
pytest                    2.8.5                    py27_0  
python                    2.7.11                        0  
python-dateutil           2.5.1                    py27_0  
pytz                      2016.2                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     15.2.0                   py27_0  
qt                        4.8.7                         1  
qtawesome                 0.3.2                    py27_0  
qtconsole                 4.2.0                    py27_0  
qtpy                      1.0                      py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.9.1                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.5                     <pip>
scikit-image              0.12.3              np110py27_0  
scikit-learn              0.17.1              np110py27_0  
scipy                     0.17.0              np110py27_2  
setuptools                20.3                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.5                    py27_0  
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0  
spyder                    2.3.8                    py27_1  
sqlalchemy                1.0.12                   py27_0  
sqlite                    3.9.2                         0  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1               np110py27_0  
sympy                     1.0                      py27_0  
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_1  
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.3                      py27_0  
traitlets                 4.2.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
util-linux                2.21                          0  
werkzeug                  0.11.4                   py27_0  
wheel                     0.29.0                   py27_0  
xlrd                      0.9.4                    py27_0  
xlsxwriter                0.8.4                    py27_0  
xlwt                      1.0.0                    py27_0  
xz                        5.0.5                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  
```

**Comment by willwhitney** [comment]
I'm having the same problem using Python 3.5.1.

**Comment by felciano** [comment]
I'm seeing this as well. Any suggestions?

**Comment by jakirkham** [comment]
Sorry, I have not had time to look at late. It seems like something has changed in one of our dependencies and we need to adjust accordingly.

**Comment by faudi** [comment]
try using 
`runipyx.ipynb
jupyter nbconvert x.ipynb --to html`

**Comment by hsiaoyi0504** [comment]
The method @faudi mentioned works for me.
