### ISSUE TITLE
Runipy crashes on plot.ly chart cells

### ISSUE THREAD

**Issue by Netherdrake** [paulgb/runipy#137]
```
04/18/2017 12:27:28 PM INFO: Cell returned
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.5/site-packages/runipy/notebook_runner.py", line 196, in run_cell
    attr = self.MIME_MAP[mime]
KeyError: 'text/vnd.plotly.v1+html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/runipy", line 11, in <module>
    load_entry_point('runipy==0.1.5+31.g98c18de', 'console_scripts', 'runipy')()
  File "/home/user/anaconda3/lib/python3.5/site-packages/runipy/main.py", line 161, in main
    nb_runner.run_notebook(skip_exceptions=args.skip_exceptions)
  File "/home/user/anaconda3/lib/python3.5/site-packages/runipy/notebook_runner.py", line 244, in run_notebook
    self.run_cell(cell)
  File "/home/user/anaconda3/lib/python3.5/site-packages/runipy/notebook_runner.py", line 199, in run_cell
    'unhandled mime type: %s' % mime
NotImplementedError: unhandled mime type: text/vnd.plotly.v1+html
```

**Comment by timnon** [comment]
similar problem:

06/16/2017 11:37:13 AM INFO: Cell returned
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/runipy/notebook_runner.py", line 192, in run_cell
    attr = self.MIME_MAP[mime]
KeyError: 'application/vnd.plotly.v1+json'
