### ISSUE TITLE
Test Fails

### ISSUE THREAD

**Issue by quasiben** [paulgb/runipy#26]
Just ran the test on OSX/python2.7 and it fails with the following error:

```bash
F
======================================================================
FAIL: testRunNotebooks (__main__.TestRunipy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 45, in testRunNotebooks
    self.assert_notebooks_equal(expected, runner.nb)
  File "test.py", line 33, in assert_notebooks_equal
    self.assertEquals(e, a)
AssertionError: {u'ename': u'ZeroDivisionError', u'evalue': u'integer division or modulo by zero [truncated]... != {'output_type': u'pyerr', 'evalue': u'integer division or modulo by zero', 'trac [truncated]...
Diff is 2019 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 1 test in 9.115s

FAILED (failures=1)
```

**Comment by jakirkham** [comment]
@quasiben, could you please retry this on current master and see if this is still a problem?

**Comment by jakirkham** [comment]
I believe I had fixed this in here ( https://github.com/paulgb/runipy/pull/65 ). As the CI is running along nicely and I can test it out on my Mac, I am assuming this is fixed. I will close this. If I am mistaken and there still is an issue, please feel free to ping me with some more details.
