### ISSUE TITLE
Raise Empty

### ISSUE THREAD

**Issue by gabraganca** [paulgb/runipy#36]
Hi!

I am try use `runipy` on a institutional public server and I am getting this error:

```python
Traceback (most recent call last):
  File "/home/gbraganca/anaconda/bin/runipy", line 6, in <module>
    sys.exit(main())
  File "/home/gbraganca/anaconda/lib/python2.7/site-packages/runipy-0.1.0-py2.7.egg/runipy/main.py", line 81, in main
  File "/home/gbraganca/anaconda/lib/python2.7/site-packages/runipy-0.1.0-py2.7.egg/runipy/notebook_runner.py", line 180, in run_notebook
  File "/home/gbraganca/anaconda/lib/python2.7/site-packages/runipy-0.1.0-py2.7.egg/runipy/notebook_runner.py", line 100, in run_cell
  File "/home/gbraganca/anaconda/lib/python2.7/site-packages/IPython/kernel/blocking/channels.py", line 44, in get_msg
    return self._in_queue.get(block, timeout)
  File "/home/gbraganca/anaconda/lib/python2.7/Queue.py", line 176, in get
    raise Empty
Queue.Empty
```

After that it just get stuck. Do not quit. Just stay there.

The code block of  [ `notebook_runner`](https://github.com/paulgb/runipy/blob/master/runipy/notebook_runner.py) that throws an error is:

```python
            try:
                msg = self.iopub.get_msg(timeout=1)
                if msg['msg_type'] == 'status':
                    if msg['content']['execution_state'] == 'idle':
                        break
            except Empty:
                # execution state should return to idle before the queue becomes empty,
                # if it doesn't, something bad has happened
                raise
```

Since it is a public server with high load (~6), it could be that the `timeout=1` is simply not enough?

**Comment by jakirkham** [comment]
I have tried several strategies to reproduce this when simply installing the latest `ipython` from the 2.x series (2.4.1) and `runipy` (0.1.3) and was unable to do so.

If I had an older version of `ipython` and `runipy`, I found I could reliably reproduce this error. With certain version combinations, I was able to make the bug sporadic, but it would still show up about half of the time. All of these failures were on Ubuntu 12.04.

The moral of the story is update to the latest `ipython` 2.x or  and latest `runipy` and this problem goes away. If you find this is not the case, please ping me with a simple list of reqs and a reproducing example and we can take another look. Otherwise, I consider this resolved and am closing this.
