### ISSUE TITLE
runipy is broken in the current git master branch of IPython

### ISSUE THREAD

**Issue by ngoldbaum** [paulgb/runipy#48]
Apparently there have been some API changes inside of IPython that have broken runipy:

```
goldbaum at ROUS in ~/Documents/runipy on master
± nosetests
/Users/goldbaum/Documents/ipython/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
E
======================================================================
ERROR: testRunNotebooks (test.TestRunipy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/goldbaum/Documents/runipy/test.py", line 50, in testRunNotebooks
    runner.run_notebook(True)
  File "/Users/goldbaum/Documents/runipy/runipy/notebook_runner.py", line 180, in run_notebook
    self.run_cell(cell)
  File "/Users/goldbaum/Documents/runipy/runipy/notebook_runner.py", line 87, in run_cell
    self.shell.execute(cell.input)
AttributeError: 'ZMQSocketChannel' object has no attribute 'execute'
-------------------- >> begin captured stdout << ---------------------
Clear Output.ipynb

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: DEBUG: Connecting to: tcp://127.0.0.1:57464
root: DEBUG: connecting shell channel to tcp://127.0.0.1:57461
root: DEBUG: Connecting to: tcp://127.0.0.1:57461
root: DEBUG: connecting iopub channel to tcp://127.0.0.1:57462
root: DEBUG: Connecting to: tcp://127.0.0.1:57462
root: DEBUG: connecting stdin channel to tcp://127.0.0.1:57463
root: DEBUG: Connecting to: tcp://127.0.0.1:57463
root: DEBUG: connecting heartbeat channel to tcp://127.0.0.1:57465
root: INFO: Running cell:
from IPython.display import clear_output

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 2.575s

FAILED (errors=1)
```

**Comment by paulgb** [comment]
I know this will not be a satisfying fix, but in the meantime I removed 3.x from the list of supported IPython versions. I am closing this for now and using #49 to track IPython 3 support.

**Comment by jakirkham** [comment]
So, just to verify this appears to be fixed in iPython 3.x. This is further demonstrated by CI running tests with the current codebase successfully using iPython 3.x on its list of supported Python versions.
