### ISSUE TITLE
Markdown() issue 

### ISSUE THREAD

**Issue by odebeir** [paulgb/runipy#62]
I am using Travis for continuous integration in combination with runipy, which is great !
Recently I tried to use Markdown() function in a cell, but it seems that this kind of output is not handled as valid 

    Markdown('some MD text')

the stacktrace I obtained is below,

any idea how to enable Markdown with runipy ?

Thanks !

Olivier

07/16/2015 03:20:13 PM Cell returned
07/16/2015 03:20:13 PM Running cell:

Markdown(chapters_to_md())
07/16/2015 03:20:13 PM Cell returned
Traceback (most recent call last):
File "runipynbs.py", line 69, in <module>
main()
File "runipynbs.py", line 49, in main
run_notebook(nbpath)
File "runipynbs.py", line 60, in run_notebook
runner.run_notebook()
File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/runipy/notebook_runner.py", line 206, in run_notebook
self.run_cell(cell)
File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/runipy/notebook_runner.py", line 164, in run_cell
raise NotImplementedError('unhandled mime type: %s' % mime)
NotImplementedError: unhandled mime type: text/markdown

**Comment by jakirkham** [comment]
Where is this `Markdown` function coming from? Is this from iPython or an external library?

**Comment by odebeir** [comment]
it is from ipython.display module

**Comment by jakirkham** [comment]
This seems to be yet another good reason for iPython 2.x deprecation. ( https://github.com/paulgb/runipy/issues/78 ) Seems that markdown is not supported in iPython 2.x. ( https://github.com/ipython/ipython/issues/6242 )

**Comment by odebeir** [comment]
Ok, I will use *html* instead of *markdown* 
```python
IPython.display import HTML
```
thanks for the help,

**Comment by jakirkham** [comment]
In the interim, if HTML works that is great, I still plan on looking in how to get Markdown to work without breaking iPython 2.x support.
